name: mruby-math CI

on:
  push:
    branches:
      - master
    paths:
      - 'mruby-math/**'
  pull_request:
    branches:
      - master
    paths:
      - 'mruby-math/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-math-${{ hashFiles('**/Cargo.lock') }}
      # - name: Install C compiler
      #   run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Run formatter
        run: |
          cargo fmt -p mrubyedge-math --check
      - name: Run tests for "${{ matrix.BUILD_TARGET }}" profile
        run: |
          cargo test -p mrubyedge-math \
            --profile ${{ matrix.BUILD_TARGET }}
      - name: Build binaries for "${{ matrix.BUILD_TARGET }}" profile
        run: |
          cargo build -p mrubyedge-math \
            --profile ${{ matrix.BUILD_TARGET }}
