name: mruby/edge CI

on:
  push:
    branches:
      - master
    paths:
      - 'mrubyedge/**'
      - 'mrubyedge-cli/**'
  pull_request:
    branches:
      - master
    paths:
      - 'mrubyedge/**'
      - 'mrubyedge-cli/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
        ENABLE_FNV_HASH: ["", ",mruby-hash-fnv"]
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Run formatter
        run: |
          set -e
          cargo fmt -p mrubyedge --check
          cargo fmt -p mrubyedge-cli --check
      - name: Run tests for "${{ matrix.BUILD_TARGET }}${{ matrix.ENABLE_FNV_HASH }}" profile
        run: |
          set +e
          cargo test -p mrubyedge \
            --features "mrubyedge-debug,mruby-random,mruby-regexp${{ matrix.ENABLE_FNV_HASH }}" \
            --profile ${{ matrix.BUILD_TARGET }}
          TEST_RESULT=$?
          if [ $TEST_RESULT != 0 ]; then
            echo "Some tests failed. Debug:"
            git diff
            exit $TEST_RESULT
          fi
      - name: Build binaries for "${{ matrix.BUILD_TARGET }}${{ matrix.ENABLE_FNV_HASH }}" profile
        run: |
          cargo build -p mrubyedge \
            --features "mrubyedge-debug,mruby-random,mruby-regexp${{ matrix.ENABLE_FNV_HASH }}" \
            --profile ${{ matrix.BUILD_TARGET }}
          cargo build -p mrubyedge-cli

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Run linter
        run: cargo clippy -p mrubyedge --features "mruby-random,mruby-regexp"